Webservices
TBoileau/key-privilege pull request #252
Opened 2021-10-05 13:20 UTC by Pompidup

2021-10-06 07:44 UTC, TBoileau requested changes

2021-10-06 07:44 UTC, TBoileau commented on public/webservice_commande.php
> +    $totalTTC = $totalHT * 1.196;
La TVA n'est plus à 19,6% depuis un moment maintenant

2021-10-06 07:44 UTC, TBoileau commented on public/webservice_commande.php
> +            "PPGC" => strval($line->getPurchasePrice()),
Ne pas oublier le `/ 100` pour mettre les valeurs en euros et non en centimes

2021-10-06 21:54 UTC, Pompidup commented on public/webservice_commande.php
> +            "PPGC" => strval($line->getPurchasePrice()),
Dans la mesure ou les prix envoyé par spéculoos ne sont pas en centimes, que dans l'appli on utilise les valeurs en Key es que tu vois un interet a renvoyer en centimes?

2021-10-06 21:58 UTC, Pompidup commented on public/webservice_commande.php
> +    $totalTTC = $totalHT * 1.196;
Ok j'ai effectué ma maj concernant les taux de tva (Ça a fait beaucoup rire Vincent et Joël), j'ai corrigé pour passer a 20%

2021-10-12 09:16 UTC, TBoileau approved these changes

2021-10-12 09:23 UTC, merged